### 
# Base URL variable
@baseUrl = http://localhost:8080
@movieId = 51

### 
# GET request – Fetch all movies
GET {{baseUrl}}/movies?page=1&size=5
Accept: application/json

### 
# GET request – Fetch all movies
GET {{baseUrl}}/movies?page=2&size=10
Accept: application/json

### 
# GET request – Fetch a single movie by ID
GET {{baseUrl}}/movies/1
Accept: application/json

### 
# GET request – Fetch a single movie by ID
GET {{baseUrl}}/movies/{{movieId}}
Accept: application/json

### 
# movie request – Create a new movie
POST {{baseUrl}}/movies
Content-Type: application/json

{
	"id": -1,
  "title": "My new movie",
	"year": 2025,
  "description": "This is a test movie created from VS Code REST Client."
}

### 
# PUT request – Update an existing movie
PUT {{baseUrl}}/movies/{{movieId}}
Content-Type: application/json

{
	"id": -1,
  "title": "Machete",
	"year": 2025,
  "description": "The best movie ever made."
}

### 
# DELETE request – Remove a movie
DELETE {{baseUrl}}/movies/1
